global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['apigateway:80']
    metrics_path: '/metrics'
    
  - job_name: 'product-service'
    static_configs:
      - targets: ['productservice:80']
    metrics_path: '/metrics'
    
  - job_name: 'order-service'
    static_configs:
      - targets: ['orderservice:80']
    metrics_path: '/metrics'
    
  - job_name: 'customer-service'
    static_configs:
      - targets: ['customerservice:80']
    metrics_path: '/metrics'